apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-conf
data:
  env: |
    MONGO_DSN=mongodb://root:root@mongodb/nest?authSource=admin
    KAFKA_CLIENT_ID=code-delivery
    KAFKA_BROKER=pkc-lzvrd.us-west4.gcp.confluent.cloud:9092
    KAFKA_CONSUMER_GROUP_ID=code-delivery
    KAFKA_SASL_USERNAME=EBNIKUAMEB2PJ2TZ
    KAFKA_SASL_PASSWORD=59VVz1gr7l4tl4ikK4Lzlk/vLZB++7ek5vOC73cxtNsKLW7oUtbfxj/PicpbZ9rq